FROM --platform=$BUILDPLATFORM golang AS build
ENV GOOS=linux
ENV CGO_ENABLED=1
ARG TARGETPLATFORM
ARG BUILDPLATFORM
WORKDIR /go/src/github.com/kennedyoliveira/prometheus-msi-afterburner-exporter
COPY ./ ./
RUN make build

FROM alpine
COPY --from=build /go/src/github.com/kennedyoliveira/prometheus-msi-afterburner-exporter/bin/prometheus-msi-afterburner-exporter /bin/

ENTRYPOINT [ "/bin/prometheus-msi-afterburner-exporter" ]